name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    name: Checks code style and run tests

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check code style
        run: flake8 .
      - name: Run tests and collect coverage
        run: pytest --cov .
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3